### ISSUE TITLE
EntryElement doesn't call DequeueReusableCell

### ISSUE THREAD

**Issue by danmiser** [migueldeicaza/MonoTouch.Dialog#237]
This seems to run against all of the docs that I can find on GetCell(). Is there a specific reason this pattern isn't being followed for the EntryElement?

**Comment by migueldeicaza** [comment]
I believe that this was due to  too much state to reset on the entry, so I just pay the price for every entry, it is not as reusable, but I did not think that there woudl be too many entry elements created, so the price was fine.
